-- database/schema.sql
-- Database Schema for SGP-II AI-Augmented Decision-Support Sandbox
-- Compatible with SQLite (local development) and PostgreSQL (cloud serverless, e.g. Neon)

-- Table to cache company fundamentals from weekly screeners
CREATE TABLE IF NOT EXISTS company_fundamentals (
    ticker TEXT PRIMARY KEY,
    pe_ratio REAL,
    debt_to_equity REAL,
    operating_margin REAL,
    roe REAL,
    is_healthy INTEGER DEFAULT 1, -- 1 for True, 0 for False (standard SQLite boolean)
    cautionary_remark TEXT, -- Explanatory remark when high debt is qualified by strong future demand
    last_updated DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table to store daily news sentiment calculated by n8n pre-market workflow
CREATE TABLE IF NOT EXISTS daily_sentiment (
    date TEXT PRIMARY KEY, -- Date formatted as YYYY-MM-DD
    sentiment_score REAL NOT NULL, -- Numeric score between -1.0 and 1.0
    sentiment_label TEXT NOT NULL, -- e.g., 'bullish', 'bearish', 'neutral'
    summary TEXT, -- Summary rationale generated by the LLM
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table to log daily recommendations generated by technical model and filtered by sentiment
CREATE TABLE IF NOT EXISTS daily_recommendations (
    date TEXT, -- Date formatted as YYYY-MM-DD
    ticker TEXT,
    signal_type TEXT, -- 'BUY', 'SELL', 'HOLD'
    prob_buy REAL, -- Probability of BUY target from ML model
    prob_sell REAL, -- Probability of SELL target
    prob_hold REAL, -- Probability of HOLD target
    sentiment_score REAL, -- Daily overnight sentiment score applied as execution filter
    is_sentiment_passed INTEGER, -- 1 if sentiment passes threshold (> 0.2 for BUY, < -0.2 for SELL), else 0
    execution_price REAL, -- Yesterday's closing price
    rationale TEXT, -- Narrative explaining the indicator and sentiment alignment
    PRIMARY KEY (date, ticker)
);
